def all_sqs():
    n = 0
    while True:
        yield n*n
        n += 1

sqs_infinite = all_sqs()

print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))
print(next(sqs_infinite))